const embed = new Discord.RichEmbed()
.setURL("https://github.com/ITZRais/Kataline-Bot")
.setAuthor("Bot Help", "https://i.imgur.com/iFkFPdM.png","https://i.imgur.com/iFkFPdM.png")
.setColor(#ac2020)
.addField("Currency")
.addField("''")
.addField("Moderation")
.addField("''")
.addField("Fun")
.addField("''")
.addField("Other")
.addField("'help, ping, test(Error)'")
.setFooter("Kataline Bot V.0.0.1, https://i.imgur.com/iFkFPdM.png")
.setTimestamp()
message.channel.send({embed})
